// flow-typed signature: a1d59da4ea705c1b48f908a4e1361f78
// flow-typed version: <<STUB>>/inferno-component_v^1.4.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-component/dist-es/index' {
  declare module.exports: any;
}

declare module 'inferno-component/dist/inferno-component' {
  declare module.exports: any;
}

declare module 'inferno-component/dist/inferno-component.min' {
  declare module.exports: any;
}

declare module 'inferno-component/dist/inferno-component.node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-component/dist-es/index.js' {
  declare module.exports: $Exports<'inferno-component/dist-es/index'>;
}
declare module 'inferno-component/dist/inferno-component.js' {
  declare module.exports: $Exports<'inferno-component/dist/inferno-component'>;
}
declare module 'inferno-component/dist/inferno-component.min.js' {
  declare module.exports: $Exports<'inferno-component/dist/inferno-component.min'>;
}
declare module 'inferno-component/dist/inferno-component.node.js' {
  declare module.exports: $Exports<'inferno-component/dist/inferno-component.node'>;
}
