// flow-typed signature: 5190b33e6d30eea78001fcf2f97d7101
// flow-typed version: <<STUB>>/inferno_v^1.4.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno/__benchmarks__/createvnode' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/core/normalization' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/core/options' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/core/structures' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/core/VNodes' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/constants' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/events/delegation' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/events/linkEvent' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/hydration' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/mounting' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/patching' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/recycling' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/rendering' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/unmounting' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/utils' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/wrappers/InputWrapper' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/wrappers/processElement' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/wrappers/SelectWrapper' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/DOM/wrappers/TextareaWrapper' {
  declare module.exports: any;
}

declare module 'inferno/dist-es/index' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno.node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno/__benchmarks__/createvnode.js' {
  declare module.exports: $Exports<'inferno/__benchmarks__/createvnode'>;
}
declare module 'inferno/dist-es/core/normalization.js' {
  declare module.exports: $Exports<'inferno/dist-es/core/normalization'>;
}
declare module 'inferno/dist-es/core/options.js' {
  declare module.exports: $Exports<'inferno/dist-es/core/options'>;
}
declare module 'inferno/dist-es/core/structures.js' {
  declare module.exports: $Exports<'inferno/dist-es/core/structures'>;
}
declare module 'inferno/dist-es/core/VNodes.js' {
  declare module.exports: $Exports<'inferno/dist-es/core/VNodes'>;
}
declare module 'inferno/dist-es/DOM/constants.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/constants'>;
}
declare module 'inferno/dist-es/DOM/events/delegation.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/events/delegation'>;
}
declare module 'inferno/dist-es/DOM/events/linkEvent.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/events/linkEvent'>;
}
declare module 'inferno/dist-es/DOM/hydration.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/hydration'>;
}
declare module 'inferno/dist-es/DOM/mounting.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/mounting'>;
}
declare module 'inferno/dist-es/DOM/patching.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/patching'>;
}
declare module 'inferno/dist-es/DOM/recycling.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/recycling'>;
}
declare module 'inferno/dist-es/DOM/rendering.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/rendering'>;
}
declare module 'inferno/dist-es/DOM/unmounting.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/unmounting'>;
}
declare module 'inferno/dist-es/DOM/utils.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/utils'>;
}
declare module 'inferno/dist-es/DOM/wrappers/InputWrapper.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/wrappers/InputWrapper'>;
}
declare module 'inferno/dist-es/DOM/wrappers/processElement.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/wrappers/processElement'>;
}
declare module 'inferno/dist-es/DOM/wrappers/SelectWrapper.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/wrappers/SelectWrapper'>;
}
declare module 'inferno/dist-es/DOM/wrappers/TextareaWrapper.js' {
  declare module.exports: $Exports<'inferno/dist-es/DOM/wrappers/TextareaWrapper'>;
}
declare module 'inferno/dist-es/index.js' {
  declare module.exports: $Exports<'inferno/dist-es/index'>;
}
declare module 'inferno/dist/inferno.js' {
  declare module.exports: $Exports<'inferno/dist/inferno'>;
}
declare module 'inferno/dist/inferno.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno.min'>;
}
declare module 'inferno/dist/inferno.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno.node'>;
}
