// flow-typed signature: 072c87c39e481ee1607f1b7705d68c96
// flow-typed version: <<STUB>>/inferno-compat_v^1.4.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-compat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-compat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-compat/dist-es/index' {
  declare module.exports: any;
}

declare module 'inferno-compat/dist-es/isValidElement' {
  declare module.exports: any;
}

declare module 'inferno-compat/dist-es/SVGDOMPropertyConfig' {
  declare module.exports: any;
}

declare module 'inferno-compat/dist/inferno-compat' {
  declare module.exports: any;
}

declare module 'inferno-compat/dist/inferno-compat.min' {
  declare module.exports: any;
}

declare module 'inferno-compat/dist/inferno-compat.node' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/EventConstants' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/EventPluginHub' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/EventPluginUtils' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/EventPropagators' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/ReactCSSTransitionGroup' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/ReactFragment' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/ReactMount' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/ReactTransitionEvents' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/ReactTransitionGroup' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/shallowCompare' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/SyntheticUIEvent' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/ViewportMetrics' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-compat/dist-es/index.js' {
  declare module.exports: $Exports<'inferno-compat/dist-es/index'>;
}
declare module 'inferno-compat/dist-es/isValidElement.js' {
  declare module.exports: $Exports<'inferno-compat/dist-es/isValidElement'>;
}
declare module 'inferno-compat/dist-es/SVGDOMPropertyConfig.js' {
  declare module.exports: $Exports<'inferno-compat/dist-es/SVGDOMPropertyConfig'>;
}
declare module 'inferno-compat/dist/inferno-compat.js' {
  declare module.exports: $Exports<'inferno-compat/dist/inferno-compat'>;
}
declare module 'inferno-compat/dist/inferno-compat.min.js' {
  declare module.exports: $Exports<'inferno-compat/dist/inferno-compat.min'>;
}
declare module 'inferno-compat/dist/inferno-compat.node.js' {
  declare module.exports: $Exports<'inferno-compat/dist/inferno-compat.node'>;
}
declare module 'inferno-compat/lib/EventConstants.js' {
  declare module.exports: $Exports<'inferno-compat/lib/EventConstants'>;
}
declare module 'inferno-compat/lib/EventPluginHub.js' {
  declare module.exports: $Exports<'inferno-compat/lib/EventPluginHub'>;
}
declare module 'inferno-compat/lib/EventPluginUtils.js' {
  declare module.exports: $Exports<'inferno-compat/lib/EventPluginUtils'>;
}
declare module 'inferno-compat/lib/EventPropagators.js' {
  declare module.exports: $Exports<'inferno-compat/lib/EventPropagators'>;
}
declare module 'inferno-compat/lib/ReactCSSTransitionGroup.js' {
  declare module.exports: $Exports<'inferno-compat/lib/ReactCSSTransitionGroup'>;
}
declare module 'inferno-compat/lib/ReactFragment.js' {
  declare module.exports: $Exports<'inferno-compat/lib/ReactFragment'>;
}
declare module 'inferno-compat/lib/ReactMount.js' {
  declare module.exports: $Exports<'inferno-compat/lib/ReactMount'>;
}
declare module 'inferno-compat/lib/ReactTransitionEvents.js' {
  declare module.exports: $Exports<'inferno-compat/lib/ReactTransitionEvents'>;
}
declare module 'inferno-compat/lib/ReactTransitionGroup.js' {
  declare module.exports: $Exports<'inferno-compat/lib/ReactTransitionGroup'>;
}
declare module 'inferno-compat/lib/shallowCompare.js' {
  declare module.exports: $Exports<'inferno-compat/lib/shallowCompare'>;
}
declare module 'inferno-compat/lib/SyntheticUIEvent.js' {
  declare module.exports: $Exports<'inferno-compat/lib/SyntheticUIEvent'>;
}
declare module 'inferno-compat/lib/ViewportMetrics.js' {
  declare module.exports: $Exports<'inferno-compat/lib/ViewportMetrics'>;
}
