// flow-typed signature: c6856b832bdd673ea7a4c636c7f41c7f
// flow-typed version: <<STUB>>/inferno-router_v^1.4.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-router/dist-es/createRoutes' {
  declare module.exports: any;
}

declare module 'inferno-router/dist-es/index' {
  declare module.exports: any;
}

declare module 'inferno-router/dist-es/IndexLink' {
  declare module.exports: any;
}

declare module 'inferno-router/dist-es/IndexRoute' {
  declare module.exports: any;
}

declare module 'inferno-router/dist-es/Link' {
  declare module.exports: any;
}

declare module 'inferno-router/dist-es/match' {
  declare module.exports: any;
}

declare module 'inferno-router/dist-es/Redirect' {
  declare module.exports: any;
}

declare module 'inferno-router/dist-es/Route' {
  declare module.exports: any;
}

declare module 'inferno-router/dist-es/Router' {
  declare module.exports: any;
}

declare module 'inferno-router/dist-es/RouterContext' {
  declare module.exports: any;
}

declare module 'inferno-router/dist-es/utils' {
  declare module.exports: any;
}

declare module 'inferno-router/dist/inferno-router' {
  declare module.exports: any;
}

declare module 'inferno-router/dist/inferno-router.min' {
  declare module.exports: any;
}

declare module 'inferno-router/dist/inferno-router.node' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/IndexLink' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/IndexRedirect' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/IndexRoute' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/Link' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/match' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/Redirect' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/Route' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/Router' {
  declare module.exports: any;
}

declare module 'inferno-router/lib/RouterContext' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-router/dist-es/createRoutes.js' {
  declare module.exports: $Exports<'inferno-router/dist-es/createRoutes'>;
}
declare module 'inferno-router/dist-es/index.js' {
  declare module.exports: $Exports<'inferno-router/dist-es/index'>;
}
declare module 'inferno-router/dist-es/IndexLink.js' {
  declare module.exports: $Exports<'inferno-router/dist-es/IndexLink'>;
}
declare module 'inferno-router/dist-es/IndexRoute.js' {
  declare module.exports: $Exports<'inferno-router/dist-es/IndexRoute'>;
}
declare module 'inferno-router/dist-es/Link.js' {
  declare module.exports: $Exports<'inferno-router/dist-es/Link'>;
}
declare module 'inferno-router/dist-es/match.js' {
  declare module.exports: $Exports<'inferno-router/dist-es/match'>;
}
declare module 'inferno-router/dist-es/Redirect.js' {
  declare module.exports: $Exports<'inferno-router/dist-es/Redirect'>;
}
declare module 'inferno-router/dist-es/Route.js' {
  declare module.exports: $Exports<'inferno-router/dist-es/Route'>;
}
declare module 'inferno-router/dist-es/Router.js' {
  declare module.exports: $Exports<'inferno-router/dist-es/Router'>;
}
declare module 'inferno-router/dist-es/RouterContext.js' {
  declare module.exports: $Exports<'inferno-router/dist-es/RouterContext'>;
}
declare module 'inferno-router/dist-es/utils.js' {
  declare module.exports: $Exports<'inferno-router/dist-es/utils'>;
}
declare module 'inferno-router/dist/inferno-router.js' {
  declare module.exports: $Exports<'inferno-router/dist/inferno-router'>;
}
declare module 'inferno-router/dist/inferno-router.min.js' {
  declare module.exports: $Exports<'inferno-router/dist/inferno-router.min'>;
}
declare module 'inferno-router/dist/inferno-router.node.js' {
  declare module.exports: $Exports<'inferno-router/dist/inferno-router.node'>;
}
declare module 'inferno-router/lib/IndexLink.js' {
  declare module.exports: $Exports<'inferno-router/lib/IndexLink'>;
}
declare module 'inferno-router/lib/IndexRedirect.js' {
  declare module.exports: $Exports<'inferno-router/lib/IndexRedirect'>;
}
declare module 'inferno-router/lib/IndexRoute.js' {
  declare module.exports: $Exports<'inferno-router/lib/IndexRoute'>;
}
declare module 'inferno-router/lib/Link.js' {
  declare module.exports: $Exports<'inferno-router/lib/Link'>;
}
declare module 'inferno-router/lib/match.js' {
  declare module.exports: $Exports<'inferno-router/lib/match'>;
}
declare module 'inferno-router/lib/Redirect.js' {
  declare module.exports: $Exports<'inferno-router/lib/Redirect'>;
}
declare module 'inferno-router/lib/Route.js' {
  declare module.exports: $Exports<'inferno-router/lib/Route'>;
}
declare module 'inferno-router/lib/Router.js' {
  declare module.exports: $Exports<'inferno-router/lib/Router'>;
}
declare module 'inferno-router/lib/RouterContext.js' {
  declare module.exports: $Exports<'inferno-router/lib/RouterContext'>;
}
